### ISSUE TITLE
Feature Request: Personalized images

### ISSUE THREAD

**Issue by markchadwick** [gsf/dewr#1]
dewr is cool. I like dewr. I often find myself wanting something like tmux installed. Oh, and my tmuxrc so I can get sane key bindings. You know, compile in one window, check build artifacts in another. And, boy, and I could `useradd -u 1000 mchadwick` and have it chown /opt/app etc etc etc...

I'm happy to write the patch, but I'd like feedback on the implementation. The idea would be if dewr finds a ~/.dewr/postinstall.Dockerfile, it will....
* `docker build - < $(cat ci/Dockerfile ~/.dewr/postinstall.Dockerfile)` ?
* Build a base image, say `myapp` then if the Blessed File Exists the `build` command will also create a `myapp.sh` to use when dropping into a shell?
* Blindly contacts the two files and just uses that for the base image?

**Comment by natlownes** [comment]
I like this idea since I have a buncha bozo shit I'm used to in the shell.  maybe the onbuild instruction would be useful https://docs.docker.com/engine/reference/builder/#onbuild

**Comment by gsf** [comment]
Got this in the monorepo
